name: raddle

services:
  mongo:
    image: mongo:7
    container_name: local-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - raddle-network

  mongo-express:
    image: mongo-express:1
    container_name: local-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Router
      - "traefik.http.routers.raddle-express.rule=Host(`${EXPRESS_URL}`)"
      - "traefik.http.routers.raddle-express.entrypoints=websecure"
      - "traefik.http.routers.raddle-express.tls.certresolver=letsencrypt"
    depends_on:
      - mongo
    networks:
      - raddle-network
      - traefik

  website:
    build:
      context: ../../
      dockerfile: apps/website/Dockerfile
    container_name: raddle-website
    ports:
      - "3000:3000"
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_PASS: example
      MONGODB_USER: root
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Router
      - "traefik.http.routers.raddle-website.rule=Host(`${DEV_URL}`)"
      - "traefik.http.routers.raddle-website.entrypoints=websecure"
      - "traefik.http.routers.raddle-website.tls.certresolver=letsencrypt"

    depends_on:
      - api
    networks:
      - raddle-network
      - traefik

  website-maintenance:
    build:
      context: ../../
      dockerfile: apps/website-maintenance/Dockerfile
    container_name: website-maintenance
    ports:
      - "3001:3000"
    networks:
      - raddle-network
      - traefik

  api:
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
    container_name: api
    ports:
      - "3002:3000"
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_PASS: example
      MONGODB_USER: root
      BUNGIE_CLIENT_ID: ${BUNGIE_CLIENT_ID}
      BUNGIE_API_KEY: ${BUNGIE_API_KEY}
      BUNGIE_REDIRECT_URI: ${BUNGIE_REDIRECT_URI}
      WEBSITE_URL: ${WEBSITE_URL}
      JWT_SECRET: ${JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Router
      - "traefik.http.routers.raddle-api.rule=Host(`${DEV_URL}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.raddle-api.entrypoints=websecure"
      - "traefik.http.routers.raddle-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.raddle-api.priority=100"

      # Middleware
      - "traefik.http.middlewares.raddle-api-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.raddle-api.middlewares=raddle-api-strip-prefix"
    depends_on:
      - mongo
    networks:
      - raddle-network
      - traefik

networks:
  raddle-network:
    name: raddle-network
  traefik:
    external: true

volumes:
  mongo_data: