name: Validate "raddle-api" Builds on "raddle-api-app" push

on:
  push:
    branches: [ "raddle-api-app" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/api/Dockerfile
          tags: raddle-api:test
          load: true
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          

      - name: List files in image
        run: |
          docker run --rm raddle-api:test ls -R /app